### ISSUE TITLE
direct download gives me erros when trying to install it

### ISSUE THREAD

**Issue by a-a3458** [Inve1951/BetterDiscordStuff#126] opened 2021-04-18 00:16 UTC
![1](https://user-images.githubusercontent.com/64805690/115130015-5d672280-9fb1-11eb-8a53-8ef5e4a4d486.PNG)

**Comment by hkstrydrx** [comment] 2021-04-19 13:46
duplicate of #125

**Comment by Inve1951** [comment] 2021-09-05 00:09
See #122

**Closed by Inve1951** 2021-09-05 00:09 UTC
Labels: duplicate
