### ISSUE TITLE
QuickDeleteMessages: META not found

### ISSUE THREAD

**Issue by sxnfulv2** [Inve1951/BetterDiscordStuff#97] opened 2020-03-30 04:46 UTC
[Image of the issue.](https://i.vgy.me/1qrvo6.png)

Reinstalling BD did not work.

**Comment by Glaived** [comment] 2020-04-01 03:15
Duplicate of #98

**Comment by Inve1951** [comment] 2020-09-28 13:48
`META not found` indicates that your copy of the plugin file is corrupt/empty. A redownload should fix it.

**Closed by Inve1951** 2020-09-28 13:48 UTC
