### ISSUE TITLE
Quick Delete Messages [Issue Report]

### ISSUE THREAD

**Issue by Torream** [Inve1951/BetterDiscordStuff#71] opened 2019-09-11 01:46 UTC
Doesn't work on BandagedBD.

**Comment by NocFA** [comment] 2019-09-11 21:32
Yep, no longer functioning on latest discord update, was working fine before it.

**Comment by Ventjuh** [comment] 2019-09-11 22:04
The same problem here, worked great until the last discord update.

**Comment by Menelwenn** [comment] 2019-09-13 21:17
https://github.com/Inve1951/BetterDiscordStuff/issues/70#issuecomment-530481556

This should fix it, it did for me, thanks Nox.git

**Comment by Inve1951** [comment] 2019-10-08 08:27
Duplicate of #70.

**Closed by Inve1951** 2019-10-08 08:27 UTC
Labels: duplicate
