### ISSUE TITLE
DirectDownload doesn't allow videos to be played

### ISSUE THREAD

**Issue by HYPExMon5ter** [Inve1951/BetterDiscordStuff#23] opened 2018-03-13 00:11 UTC
https://gfycat.com/DeficientDisastrousHylaeosaurus
as you see here, it tries to download it, but doesn't, just pops up a blank box like it did download it, and doesn't play, play's fine without DirectDownload enabled.

**Comment by Inve1951** [comment] 2018-03-14 18:09
are you using the lastest version? (0.3.6)

**Comment by HYPExMon5ter** [comment] 2018-03-14 18:11
Yes

**Comment by Inve1951** [comment] 2018-03-14 18:13
i can't reproduce
when i click the _gif_ in chat it opens the modal as it should
it plays automatically or on hover, depending on your setting
clicking it in the modal downloads it just fine

**Comment by Inve1951** [comment] 2018-03-14 18:14
oh, i thought your gfycat link is what's broken....

**Comment by Inve1951** [comment] 2018-03-14 18:15
get me the broken link/video file
discord square#3880

**Comment by Inve1951** [comment] 2018-03-14 19:50
fixed in 0.3.7

**Closed by Inve1951** 2018-03-14 19:50 UTC
Labels: need-more-info
