### ISSUE TITLE
scrollToLast not working

### ISSUE THREAD

**Issue by narwall101** [Inve1951/BetterDiscordStuff#171] opened 2022-05-29 23:13 UTC
The plugin no longer scroll to the most recent message

**Comment by maenDisease** [comment] 2022-05-30 02:24
Duplicate of #80

**Comment by amxmu** [comment] 2022-06-06 12:54
Yeah I commented on an older post because the issue has reoccured. The plugin hasn't been working since the first time I commented on #80. Discord itself has a function in which you hit Esc on a text channel to go down to the bottom. Thats the "fix" till Square takes a look at the plugin

**Comment by Inve1951** [comment] 2022-07-31 18:58
Closing as duplicate.

**Closed by Inve1951** 2022-07-31 18:58 UTC
