### ISSUE TITLE
[Plugin] QuickDeleteMessages.

### ISSUE THREAD

**Issue by barbiehunter** [Inve1951/BetterDiscordStuff#75] opened 2019-09-25 15:13 UTC
The Plugin ( https://github.com/Inve1951/BetterDiscordStuff/blob/master/coffee/QuickDeleteMessages.plugin.coffee ) Dont work anymore, would be Nice if you look whats wrong, that it will work again.

**Comment by Insan1ty0ne** [comment] 2019-10-04 22:27
I second this, on the latest canary builds this plugin hasn't worked for at least 3 or 4 weeks. Please update it!

**Comment by Inve1951** [comment] 2019-10-08 08:28
Duplicate of #70.

**Closed by Inve1951** 2019-10-08 08:28 UTC
