### ISSUE TITLE
Channel History plugin moves forward/back by two channels instead of one

### ISSUE THREAD

**Issue by XepherTim** [Inve1951/BetterDiscordStuff#106] opened 2020-08-09 16:20 UTC
Started happening relatively recently, could be related to a Discord update, idk.

Using a Logitech G502 Hero, tried unbinding "forward" and "back" from the side buttons, then they don't do anything.

Tried binding "forward" and "back" to extra keys on my keyboard, acts the same as if they were bound to mouse, forward/back two channels instead of one.

GUI buttons work normally though.

**Comment by Inve1951** [comment] 2020-08-11 18:02
Duplicate of #105. Simply disable the plugin.

**Closed by Inve1951** 2020-08-11 18:02 UTC
