### ISSUE TITLE
QuickDeleteMessage no longer functional in latest stable discord version

### ISSUE THREAD

**Issue by jack652** [Inve1951/BetterDiscordStuff#102] opened 2020-05-30 16:22 UTC
The plugin starts but does not function

**Comment by PythonCoderAS** [comment] 2020-08-18 02:44
Same

**Comment by espionage1337** [comment] 2020-09-07 16:33
Still not fixed

**Comment by PythonCoderAS** [comment] 2020-09-07 16:34
> Still not fixed

Just hold shift, you can now 1-click delete messages. Official latest stable build.

**Comment by Inve1951** [comment] 2020-09-17 15:50
> Just hold shift, you can now 1-click delete messages. Official latest stable build.
Shift-clicking delete in the message's menu has always deleted without confirmation as far as I'm aware of.

Closing as duplicate of #84.
I'll merge the pending PR momentarily (v1.4.2).

**Closed by Inve1951** 2020-09-17 15:50 UTC
