### ISSUE TITLE
charCounter disappears when switching rooms/servers

### ISSUE THREAD

**Issue by Drflash55** [Inve1951/BetterDiscordStuff#10] opened 2017-10-27 20:16 UTC
charCounter 1.0.1 works temporarily with the new Discord Stable update.
It appears in the bottom-right as normal, but when switching channels, or servers, it vanishes and doesn't come back unless you re-enable the plugin.

It might be an interface issue, but I'd like it if it was given a sort of quick fix.
Thanks in advance.

**Comment by Inve1951** [comment] 2017-11-02 00:38
it's caused by a discord update and should be get fixed on BD's end

might push an update before that happens

**Closed** 2017-11-02 01:13 UTC
